# Specify the version for docker-compose.yml
version: "3.8"

# add the serivces needed (postgres,go)
services:
  app:
    container_name: api-server
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    image: yawnak/foodadvisor:v0.1.2
    command: ["-wenv", "aws"]
    ports:
      - '8080:8080'
    networks:
      - backend

networks:
  backend:
    driver: bridge
